<a href="https://colab.research.google.com/github/BhammarArjun/PyTorch/blob/main/PyTorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tensor - Multi-dimensional Array
# Default - float32

In [2]:
import torch
import numpy

In [4]:
## List data structure -- can have any type of datatype in it

my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [7]:
## Numpy Array

np1 = numpy.random.rand(3,4)
print(np1)

[[0.69485338 0.86731914 0.88762187 0.66247422]
 [0.16335814 0.45524503 0.63154193 0.08034911]
 [0.81277062 0.85758496 0.07404047 0.46904819]]


In [6]:
np1.dtype

dtype('float64')

In [8]:
## Creating Tensors

torch_2d = torch.randn(3,4)
torch_2d

tensor([[ 0.4179, -1.0540,  0.2784, -0.3507],
        [-0.2216,  0.4445,  0.6965, -0.2100],
        [-0.5156,  1.2943,  0.8785,  0.7407]])

In [11]:
tensor_3d = torch.zeros(2,3,3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
tensor_3d.dtype

torch.float32

In [12]:
## Create tensor from np array

torch.from_numpy(np1)

tensor([[0.6949, 0.8673, 0.8876, 0.6625],
        [0.1634, 0.4552, 0.6315, 0.0803],
        [0.8128, 0.8576, 0.0740, 0.4690]], dtype=torch.float64)

In [13]:
torch.Tensor(np1)

tensor([[0.6949, 0.8673, 0.8876, 0.6625],
        [0.1634, 0.4552, 0.6315, 0.0803],
        [0.8128, 0.8576, 0.0740, 0.4690]])

In [15]:
## Tensor is for holding data for deep learning - that's it bro

In [16]:
## Thanks, Bye