<a href="https://colab.research.google.com/github/BhammarArjun/PyTorch/blob/main/PyTorch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Let's See some of the Operations in PyTorch

In [2]:
import torch

In [7]:
 aa = torch.arange(10)
 aa

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
## Do reshape

aa = aa.reshape(2,5)
aa

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
## Use -1 to reshape

tensor2 = torch.arange(10)

tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

-1 value automatically decides units in that dimension. But N*M should be equal to original dimensions

In [13]:
tensor2 = tensor2.reshape(5,-1)
tensor2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [14]:
tensor3 = torch.arange(20)
tensor3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [15]:
tensor3.view(2,10)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
# Reshape or View can be used

In [18]:
tensor4 = tensor3.reshape(2,10)
tensor4

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
tensor3[1] = 500

print(tensor3)

print(tensor4)

tensor([  0, 500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19])
tensor([[  0, 500,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]])


In [22]:
# Changes in original tensor are updated

In [23]:
tensor6 = torch.arange(10)
tensor6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
tensor6[7]

tensor(7)

In [28]:
tensor7 = tensor6.reshape(5,2)
tensor7


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [29]:
tensor7[:,1]

tensor([1, 3, 5, 7, 9])

In [30]:
## Returning columns
tensor7[:,1:2]


tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [31]:
## Thanks