<a href="https://colab.research.google.com/github/BhammarArjun/PyTorch/blob/main/PyTorch4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
## Addition

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
## Multiplication

tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [7]:
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [8]:
tensor_c = torch.tensor([1,2,4,3])

In [ ]:
torch.multiply(tensor_a, tensor_b, tensor_c)
# This will give error because it takes two tensors at a time

In [11]:
## Division

tensor_1 = tensor_b / tensor_a

tensor_1.dtype

torch.float32

In [12]:
## Modulus operation

tensor_b % tensor_a   #(torch.remainder)

tensor([0, 0, 1, 0])

In [15]:
## Exponent operation

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [17]:
tensor_a.add_(tensor_b) # this will change original tensor

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a.add(tensor_b) # this will not change original tensor

tensor([11, 14, 17, 20])

In [20]:
tensor_a

tensor([ 6,  8, 10, 12])